
from __future__ import annotations
from pathlib import Path
import math
import numpy as np
from .volumetric import J_from_x, hydrostatic_pressure_from_K


def export_excel_calculator(model, params, datasets, fit_result, path):
    """Create an Excel workbook with fitted parameters and prediction lookup tabs.

    It is intentionally robust for all supported model files: the GUI/Python kernel
    computes the prediction table, while the User_Calculator sheet uses Excel 365
    formulas to interpolate the exported prediction grid.
    """
    path=Path(path); path.parent.mkdir(parents=True, exist_ok=True)
    try:
        import xlsxwriter
    except Exception as e:
        raise RuntimeError('xlsxwriter is required to export the Excel calculator. Install requirements.txt again.') from e

    wb=xlsxwriter.Workbook(str(path))
    title_fmt=wb.add_format({'bold':True,'font_size':18,'font_color':'#0f172a'})
    h_fmt=wb.add_format({'bold':True,'bg_color':'#eff6ff','border':1,'font_color':'#0f172a'})
    cell_fmt=wb.add_format({'border':1})
    num_fmt=wb.add_format({'border':1,'num_format':'0.000000E+00'})
    note_fmt=wb.add_format({'text_wrap':True,'font_color':'#475569'})

    # README
    ws=wb.add_worksheet('README')
    ws.set_column('A:A', 26); ws.set_column('B:B', 90)
    ws.write('A1','HyperFitPro Excel Calculator',title_fmt)
    rows=[
        ('Purpose','Stores the final fitted parameters and a prediction lookup grid generated by the Python kernel.'),
        ('How to use','Open User_Calculator, select a deformation mode and type a strain/gamma value. The formula interpolates the Prediction_Table.'),
        ('Important','For arbitrary custom hyperelastic models, the prediction grid is generated from the final fitted parameters. If parameters are edited manually, regenerate this workbook from HyperFitPro.'),
        ('Model',f'{model.number:02d} - {model.name}'),
        ('Category',model.category),
    ]
    for r,(a,b) in enumerate(rows,3):
        ws.write(r,0,a,h_fmt); ws.write(r,1,b,note_fmt)

    # Model info
    ws=wb.add_worksheet('Model_Info')
    ws.set_column('A:A',24); ws.set_column('B:B',110)
    info=[('Model number',model.number),('Model name',model.name),('Category',model.category),('Recommended tests',', '.join(model.recommended_tests)),('Equation LaTeX',model.equation_latex),('Equation with numbers',model.equation_with_numbers(params)),('Notes',model.notes)]
    for r,(a,b) in enumerate(info):
        ws.write(r,0,a,h_fmt); ws.write(r,1,str(b),cell_fmt)
    ws.set_row(4,80); ws.set_row(5,80); ws.set_row(6,80)

    # Parameters
    ws=wb.add_worksheet('Parameters')
    ws.set_column('A:A',22); ws.set_column('B:B',22); ws.set_column('C:C',55)
    ws.write_row(0,0,['Parameter','Fitted value','Description'],h_fmt)
    desc={s.name: s.description for s in model.parameter_specs}
    for r,(k,v) in enumerate(params.items(),1):
        ws.write(r,0,k,cell_fmt); ws.write_number(r,1,float(v),num_fmt); ws.write(r,2,desc.get(k,''),cell_fmt)

    # Metrics
    ws=wb.add_worksheet('Metrics')
    ws.set_column('A:A',24); ws.set_column('B:B',36)
    metric_rows=[('Success',fit_result.success),('Method',fit_result.method),('Objective',fit_result.objective),('RMSE',fit_result.rmse),('MAE',fit_result.mae),('R2',fit_result.r2),('NFEV',fit_result.nfev),('Elapsed_s',fit_result.elapsed_s)]
    for r,(a,b) in enumerate(metric_rows):
        ws.write(r,0,a,h_fmt)
        if isinstance(b,(int,float)) and not isinstance(b,bool) and math.isfinite(float(b)): ws.write_number(r,1,float(b),num_fmt)
        else: ws.write(r,1,str(b),cell_fmt)

    # Imported fit data
    ws=wb.add_worksheet('Fit_Data_Imported')
    ws.set_column('A:E',22)
    ws.write_row(0,0,['Mode','x','test stress','weight','source file'],h_fmt)
    r=1
    for d in datasets:
        for x,y in zip(d.x,d.stress):
            ws.write(r,0,d.mode,cell_fmt); ws.write_number(r,1,float(x),num_fmt); ws.write_number(r,2,float(y),num_fmt); ws.write_number(r,3,float(d.weight),cell_fmt); ws.write(r,4,Path(d.source_file).name,cell_fmt); r+=1

    # Prediction table
    ws=wb.add_worksheet('Prediction_Table')
    ws.set_column('A:C',22)
    ws.write_row(0,0,['Mode','x','predicted stress'],h_fmt)
    modes=['uniaxial','biaxial','planar','simple_shear'] + (['volumetric'] if 'K' in params else [])
    row=1
    for mode in modes:
        data_for_mode=[d for d in datasets if d.mode==mode and len(d.x)]
        if data_for_mode:
            xmin=min(float(np.nanmin(d.x)) for d in data_for_mode); xmax=max(float(np.nanmax(d.x)) for d in data_for_mode)
            pad=0.05*max(1e-9,xmax-xmin); xmin=max(-0.95,xmin-pad); xmax=xmax+pad
        else:
            xmin=0.0; xmax=1.5 if mode!='simple_shear' else 1.0
        xs=np.linspace(xmin,xmax,121)
        try:
            if mode == 'volumetric':
                ys=hydrostatic_pressure_from_K(J_from_x(xs), params['K'])
            else:
                ys=model.predict_nominal(mode,xs,params)
        except Exception:
            ys=np.full_like(xs,np.nan,dtype=float)
        for x,y in zip(xs,ys):
            ws.write(row,0,mode,cell_fmt); ws.write_number(row,1,float(x),num_fmt)
            if np.isfinite(y): ws.write_number(row,2,float(y),num_fmt)
            else: ws.write(row,2,'NaN',cell_fmt)
            row+=1
    last_pred_row=row

    # User calculator with Excel 365 dynamic arrays; fallback table is available above.
    ws=wb.add_worksheet('User_Calculator')
    ws.set_column('A:A',28); ws.set_column('B:B',34); ws.set_column('D:D',80)
    ws.write('A1','Interactive prediction calculator',title_fmt)
    ws.write('A3','Mode',h_fmt); ws.write('B3','uniaxial',cell_fmt)
    ws.data_validation('B3', {'validate':'list','source':modes})
    ws.write('A4','Input x = strain or shear gamma',h_fmt); ws.write_number('B4',0.1,num_fmt)
    ws.write('A5','Predicted nominal stress',h_fmt)
    formula = '=LET(m,$B$3,x,$B$4,xs,FILTER(Prediction_Table!$B$2:$B$%d,Prediction_Table!$A$2:$A$%d=m),ys,FILTER(Prediction_Table!$C$2:$C$%d,Prediction_Table!$A$2:$A$%d=m),FORECAST.LINEAR(x,xs,ys))' % (last_pred_row,last_pred_row,last_pred_row,last_pred_row)
    ws.write_formula('B5', formula, num_fmt)
    ws.write('D3','Note',h_fmt)
    ws.write('D4','This sheet interpolates the Prediction_Table. It is a final-parameter calculator, not a replacement for the Python optimizer.',note_fmt)

    # Chart sheet based on prediction table
    chart=wb.add_chart({'type':'scatter','subtype':'straight'})
    # Excel ranges per mode are contiguous because written block by block.
    start=2
    for mode in modes:
        end=start+121-1
        chart.add_series({'name':mode,'categories':f'=Prediction_Table!$B${start}:$B${end}','values':f'=Prediction_Table!$C${start}:$C${end}','marker':{'type':'none'}})
        start=end+1
    chart.set_title({'name':'Predicted stress curves from fitted parameters'})
    chart.set_x_axis({'name':'x = strain/gamma'}); chart.set_y_axis({'name':'nominal stress'})
    ws.insert_chart('A8',chart,{'x_scale':1.55,'y_scale':1.35})

    wb.close()
    return str(path)
