from __future__ import annotations

LANGUAGES = {
    'tr': 'Türkçe',
    'en': 'English',
    'de': 'Deutsch',
    'fr': 'Français',
    'es': 'Español',
}

TRANSLATIONS = {
    'tr': {
        'app_title': 'HyperFitPro Studio',
        'app_subtitle': 'Hiperelastik malzeme kalibrasyonu, proje kütüphanesi, plugin çalışma alanı ve FEA export stüdyosu',
        'ready': 'Hazır. Çalışma klasörü, model ve test datası ile başla.',
        'language': 'Dil', 'navigation': 'Navigasyon', 'hide': 'Gizle', 'menu': 'Menü',
        'import_project_short': 'İçe Aktar', 'save_short': 'Kaydet', 'runs_short': 'Runlar', 'checks_short': 'Kontroller', 'help_short': 'Yardım', 'open_dir_short': 'Klasör',
        'workflow': 'İş Akışı', 'plugins': 'Pluginler', 'projects': 'Projeler', 'tools': 'Araçlar',
        'dashboard': 'Dashboard', 'model': 'Model', 'data_import': 'Veri İçe Aktarma', 'optimization': 'Optimizasyon', 'report_export': 'Rapor / Export',
        'plugin_workbench': 'Plugin Workbench', 'plugin_results': 'Plugin Sonuçları', 'project_library': 'Proje Kütüphanesi', 'diagnostics': 'Doğrulama Merkezi', 'help': 'Yardım / Kullanım Kılavuzu',
        'dashboard_subtitle': 'Çalışma klasörü, aktif proje durumu, hızlı aksiyonlar ve yönlendirici akış tek ekranda.',
        'main_flow': 'Çalışma Klasörü → Model → Veri → Optimizasyon → Rapor/Export → Pluginler → Proje Kaydı',
        'guided_flow': 'Yönlendirilmiş akış',
        'workflow_overview_subtitle': 'Kalibrasyon iş akışının tüm ana adımları burada özetlenir.',
        'workflow_overview_text': 'Bu bölüm model kalibrasyonunu adım adım yürütür. Önce çalışma klasörünü seç, sonra model ve test verilerini hazırla, optimizasyonu çalıştır ve sonuçları rapor/export adımında paketle.',
        'workflow_overview_steps': '1. Dashboard: çalışma klasörü ve aktif durum kontrol edilir.\n2. Model: malzeme modeli, denklem ve parametre aralıkları incelenir.\n3. Veri: test dosyaları çoklu şekilde içeri aktarılır ve ön işleme uygulanır.\n4. Optimizasyon: önerilen veya kullanıcı tanımlı metotla parametreler bulunur.\n5. Rapor / Export: PDF, Excel calculator ve FEA dosyaları oluşturulur.',
        'plugins_overview_subtitle': 'Gömülü tool pluginleri kategori bazlı çalıştır ve çıktılarını görüntüle.',
        'plugins_overview_text': 'Plugin Workbench, aktif çalışma alanına veya daha önce kaydedilmiş projelere kalite kontrol, plot, rapor, model seçimi, FEA denetimi ve paketleme araçları uygular.',
        'plugins_overview_steps': '1. Workbench: hedef proje seçilir, kategori ve plugin belirlenir.\n2. Results: plugin çıktı dosyaları görüntülenir, HTML/PNG/CSV/TXT dosyaları önizlenir ve klasörler açılır.',
        'projects_overview_subtitle': '.hyp2fit proje dosyalarını içeri al, tekrar aç ve plugin hedefi olarak kullan.',
        'projects_overview_text': 'Proje kütüphanesi, mevcut kalibrasyonun yanında daha önce oluşturulmuş projeleri yönetir. Böylece pluginler sadece aktif projeye değil, arşiv projelerine de uygulanabilir.',
        'projects_overview_steps': '1. .hyp2fit proje dosyası içeri aktarılır.\n2. Seçili proje aktif workspace içine yüklenebilir.\n3. Aynı proje Plugin Workbench içinde hedef olarak seçilebilir.\n4. Güncel çalışma yeni .hyp2fit olarak kaydedilir.',
        'tools_overview_subtitle': 'Doğrulama ve yardım araçlarına tek merkezden ulaş.',
        'tools_overview_text': 'Araçlar bölümünde kod ve model doğrulama kontrolleri ile detaylı offline kullanım kılavuzu yer alır. GitHub yayını öncesinde Diagnostics Center kullanılması önerilir.',
        'tools_overview_steps': '1. Diagnostics: çekirdek, model kütüphanesi, veri işleme, optimizasyon, FEA export ve plugin kontrolleri çalıştırılır.\n2. Help: PDF/HTML kılavuz, anotasyonlu ekranlar ve örnek analizler açılır.',
        'working_directory': 'Çalışma klasörü', 'select': 'Seç', 'open': 'Aç', 'current_workspace': 'Aktif çalışma alanı', 'quick_actions': 'Hızlı aksiyonlar', 'recommended_workflow': 'Önerilen iş akışı', 'session_log': 'Oturum logu',
        'import_project': 'Proje içe aktar', 'load_selected_project': 'Seçili projeyi yükle', 'save_hyp2fit': '.hyp2fit kaydet', 'run_optimization': 'Optimizasyonu çalıştır', 'run_selected_plugins': 'Seçili pluginleri çalıştır', 'view_plugin_results': 'Plugin sonuçlarını görüntüle', 'diagnostics_center': 'Doğrulama merkezi', 'help_user_guide': 'Yardım / Kullanım kılavuzu',
        'workflow_guidance': '1) Çalışma klasörü seç → 2) Model seç → 3) Test verilerini içeri aktar → 4) recommended_adaptive_bounds ile fit et → 5) Plugin Workbench ile kalite/rapor/FEA araçlarını çalıştır → 6) Rapor ve export oluştur → 7) .hyp2fit proje olarak kaydet.',
        'model_selection': 'Model seçimi', 'model_subtitle': 'Model bilgisi, denklem, ham LaTeX, kalibrasyon notları ve parametre min/max aralıkları tek kaydırılabilir kutuda gösterilir.', 'search': 'Ara', 'category': 'Kategori', 'model_search_placeholder': 'Model adı, numarası, kategori veya family ara...', 'copy_model_details': 'Model detaylarını kopyala',
        'data_subtitle': 'Çoklu CSV/XLSX içeri aktar. Ham force-displacement veya işlenmiş stress-strain datası aynı panelden alınır.', 'import_settings': 'İçe aktarma ayarları', 'advanced_preprocessing': 'Gelişmiş ön işleme', 'strain_percent': 'strain kolonu % olarak verilmiş', 'zero_offset': 'sıfır-offset düzeltmesi', 'add_files': 'Bir veya birden fazla dosya ekle', 'remove_selected': 'Seçileni kaldır', 'auto_balance_weights': 'Ağırlıkları otomatik dengele',
        'mode_label': 'Mod', 'data_kind_label': 'Veri türü', 'weight_label': 'Ağırlık', 'force_unit_label': 'Kuvvet birimi', 'length_unit_label': 'Uzunluk birimi', 'stress_unit_label': 'Gerilme birimi', 'area_label': 'Alan', 'width_label': 'Genişlik', 'thickness_label': 'Kalınlık', 'diameter_label': 'Çap', 'gauge_length_label': 'Gauge length', 'branch_label': 'Dal', 'smoothing_label': 'Yumuşatma', 'window_label': 'Pencere', 'outlier_label': 'Aykırı değer', 'toe_remove_label': 'Toe silme %', 'downsample_label': 'Downsample max', 'region_weighting_label': 'Bölge ağırlığı', 'file_label': 'Dosya', 'points_label': 'Nokta', 'preprocessing_label': 'Ön işleme',
        'optimization_subtitle': 'Canlı monitörde objective, best objective, fit preview ve iterasyon tablosu eş zamanlı güncellenir.', 'run_controls': 'Run kontrolleri', 'optimization_tip': 'Öneri: önce recommended_adaptive_bounds kullan. Global metotlar uzun sürebilir; GUI çalışırken canlı plotları günceller.', 'method_label': 'Metot', 'max_evaluations_label': 'Maks. değerlendirme', 'regularization_label': 'Regularization', 'reg_type_label': 'Reg. tipi', 'validation_split_label': 'Validation bölmesi', 'workers_label': 'Worker sayısı', 'near_bound_penalty_label': 'Bound cezası', 'pause': 'Duraklat', 'stop': 'Durdur', 'eval_label': 'Eval', 'objective_label': 'Objective', 'best_objective_label': 'En iyi objective', 'parameters_label': 'Parametreler',
        'report_subtitle': 'PDF rapor, FEA export bundle, Excel calculator ve run klasörü yönetimi.', 'open_last_run_folder': 'Son run klasörünü aç', 'generate_fea_bundle': 'FEA export bundle üret/güncelle', 'generate_pdf_report': 'PDF rapor üret', 'generate_excel_calculator': 'Excel calculator üret', 'parameter_metric': 'Parametre / Metrik', 'value_label': 'Değer', 'report_note': 'Tamamlanan run sonrasında plotlar, loglar, raporlar, export dosyaları, FEA hedef eğrileri ve plugin çıktıları run klasörü altında saklanır. Ek denetim ve rapor varlıkları için Plugin Workbench kullanılır.',
        'plugin_subtitle': '50 gömülü plugin kategori bazlıdır. Aktif workspace veya içeri alınmış .hyp2fit/.hfp projeleri üzerinde çalıştırılabilir.', 'target_project': 'Hedef proje', 'reload_plugins': 'Pluginleri yenile', 'run_selected': 'Seçileni çalıştır', 'run_category': 'Kategoride uyumlu olanları çalıştır', 'plugin_categories': 'Plugin kategorileri / araçlar', 'plugin_detail': 'Plugin detayı', 'requires': 'Gereksinim', 'outputs': 'Çıktılar', 'flat_plugin_list': 'Düz plugin listesi', 'plugin_results_subtitle': 'Plugin çıktı dosyalarını burada görüntüle. Sonuçlar tools klasörlerinde saklanır.', 'time_label': 'Zaman', 'target': 'Hedef', 'plugin': 'Plugin', 'message': 'Mesaj', 'files': 'Dosyalar',
        'project_subtitle': 'Kaydedilmiş .hyp2fit veya eski .hfp projeleri içeri alınabilir; pluginler bu projelere de uygulanabilir.', 'import_hyp2fit_project': '.hyp2fit / .hfp proje içe aktar', 'load_selected_workspace': 'Seçileni workspace içine yükle', 'save_current_hyp2fit': 'Mevcut çalışmayı .hyp2fit kaydet', 'remove_selected_library': 'Seçileni kütüphaneden kaldır', 'project': 'Proje', 'datasets': 'Datasetler', 'last_run': 'Son run', 'modified': 'Değiştirilme', 'notes': 'Notlar',
        'diagnostics_subtitle': 'GitHub yayını ve kullanıcı teslimi öncesi tüm doğrulama kontrolleri bu merkezden çalıştırılır.', 'run_selected_checks': 'Seçili kontrolleri çalıştır', 'run_all_checks': 'Tüm kontrolleri çalıştır', 'clear_log': 'Logu temizle', 'available_checks': 'Mevcut doğrulama kontrolleri', 'diagnostic_note': 'Bu merkez, doğrulama kontrollerini GUI içinde toplar. Root klasörde yalnızca ana launcher dosyası kalır.', 'diagnostic_output': 'Doğrulama çıktısı',
        'help_page_title': 'Yardım / Kullanım Kılavuzu', 'help_page_subtitle': 'Offline yardım merkezi: 5 analiz örneği, anotasyonlu ekranlar, PDF/HTML manual ve sorun giderme.', 'open_pdf_manual': 'PDF manual aç', 'open_html_guide': 'HTML kılavuz aç', 'open_help_folder': 'Yardım klasörünü aç', 'capture_screenshot': 'Aktif ekran görüntüsü al', 'help_topics': 'Yardım konuları / anotasyonlu ekranlar', 'help_note': 'Bu yardım sistemi programla birlikte offline gelir. Beş analiz örneği, çok dilli yönlendirme ve vurgulamalı ekranlar içerir.', 'select_topic': 'Bir yardım konusu seç',
        'language_changed': 'Arayüz dili değiştirildi: {language}', 'no_model_data_run': 'Henüz model/veri/run yok.', 'about_title': 'HyperFitPro Studio hakkında', 'about_text': 'HyperFitPro Studio 1.0: hiperelastik malzeme kalibrasyonu, raporlama, plugin analizi ve FEA export için geliştirilmiş mühendislik çalışma ortamı.',
    },
}

# English base values are kept fully explicit for GitHub users.
TRANSLATIONS['en'] = {**TRANSLATIONS['tr'], **{
    'app_subtitle': 'Hyperelastic material calibration, project library, plugin workbench and FEA export studio',
    'ready': 'Ready. Start with working directory, model and test data.', 'language': 'Language', 'navigation': 'Navigation', 'hide': 'Hide', 'menu': 'Menu',
    'import_project_short': 'Import', 'save_short': 'Save', 'runs_short': 'Runs', 'checks_short': 'Checks', 'help_short': 'Help', 'open_dir_short': 'Open Dir',
    'workflow': 'Workflow', 'plugins': 'Plugins', 'projects': 'Projects', 'tools': 'Tools', 'dashboard': 'Dashboard', 'model': 'Model', 'data_import': 'Data Import', 'optimization': 'Optimization', 'report_export': 'Report / Export', 'plugin_workbench': 'Plugin Workbench', 'plugin_results': 'Plugin Results', 'project_library': 'Project Library', 'diagnostics': 'Diagnostics Center', 'help': 'Help / User Guide',
    'dashboard_subtitle': 'Working directory, active project state, quick actions and guided flow on a single screen.', 'main_flow': 'Working Directory → Model → Data → Optimization → Report/Export → Plugins → Save Project', 'guided_flow': 'Guided flow',
    'workflow_overview_subtitle': 'All main calibration workflow steps are summarized here.', 'workflow_overview_text': 'This section walks through model calibration step by step. Select a working directory, choose a model, import test data, run optimization and package outputs.', 'workflow_overview_steps': '1. Dashboard: check working directory and active state.\n2. Model: review material model, equation and parameter bounds.\n3. Data: import multiple test files and apply preprocessing.\n4. Optimization: identify parameters with recommended or custom methods.\n5. Report / Export: generate PDF, Excel calculator and FEA files.',
    'plugins_overview_subtitle': 'Run embedded tool plugins by category and view their outputs.', 'plugins_overview_text': 'Plugin Workbench applies quality checks, plots, reports, model-selection tools, FEA audits and packaging tools to the current workspace or imported projects.', 'plugins_overview_steps': '1. Workbench: select target project, category and plugin.\n2. Results: view plugin output files, preview HTML/PNG/CSV/TXT files and open output folders.',
    'projects_overview_subtitle': 'Import .hyp2fit projects, reopen them and use them as plugin targets.', 'projects_overview_text': 'Project Library manages previous projects as well as the active calibration. Plugins can therefore run on archived projects too.', 'projects_overview_steps': '1. Import a .hyp2fit project.\n2. Load the selected project into the active workspace.\n3. Select the same project as a Plugin Workbench target.\n4. Save the current work as a new .hyp2fit project.',
    'tools_overview_subtitle': 'Access verification and help tools from one center.', 'tools_overview_text': 'The Tools section contains validation checks and the detailed offline user guide. Run Diagnostics Center before publishing the repository.', 'tools_overview_steps': '1. Diagnostics: run core, model library, data processing, optimization, FEA export and plugin checks.\n2. Help: open PDF/HTML guide, annotated screens and worked examples.',
    'working_directory': 'Working directory', 'select': 'Select', 'open': 'Open', 'current_workspace': 'Current workspace', 'quick_actions': 'Quick actions', 'recommended_workflow': 'Recommended workflow', 'session_log': 'Session log',
    'import_project': 'Import project', 'load_selected_project': 'Load selected project', 'save_hyp2fit': 'Save .hyp2fit', 'run_optimization': 'Run optimization', 'run_selected_plugins': 'Run selected plugins', 'view_plugin_results': 'View plugin results', 'diagnostics_center': 'Diagnostics Center', 'help_user_guide': 'Help / User Guide',
    'workflow_guidance': '1) Select working directory → 2) Choose model → 3) Import test data → 4) Fit with recommended_adaptive_bounds → 5) Run quality/report/FEA tools in Plugin Workbench → 6) Generate reports and exports → 7) Save as .hyp2fit project.',
    'model_selection': 'Model selection', 'model_subtitle': 'Model information, equation, raw LaTeX, calibration notes and parameter min/max bounds are shown in one scrollable panel.', 'search': 'Search', 'category': 'Category', 'model_search_placeholder': 'Search model name, number, category or family...', 'copy_model_details': 'Copy model details',
    'data_subtitle': 'Import multiple CSV/XLSX files. Raw force-displacement or processed stress-strain data are handled in the same panel.', 'import_settings': 'Import settings', 'advanced_preprocessing': 'Advanced preprocessing', 'strain_percent': 'strain column is %', 'zero_offset': 'zero-offset correction', 'add_files': 'Add one or multiple files', 'remove_selected': 'Remove selected', 'auto_balance_weights': 'Auto-balance weights',
    'mode_label': 'Mode', 'data_kind_label': 'Data kind', 'weight_label': 'Weight', 'force_unit_label': 'Force unit', 'length_unit_label': 'Length unit', 'stress_unit_label': 'Stress unit', 'area_label': 'Area', 'width_label': 'Width', 'thickness_label': 'Thickness', 'diameter_label': 'Diameter', 'gauge_length_label': 'Gauge length', 'branch_label': 'Branch', 'smoothing_label': 'Smoothing', 'window_label': 'Window', 'outlier_label': 'Outlier', 'toe_remove_label': 'Toe remove %', 'downsample_label': 'Downsample max', 'region_weighting_label': 'Region weighting', 'file_label': 'File', 'points_label': 'Points', 'preprocessing_label': 'Preprocessing',
    'optimization_subtitle': 'Objective, best objective, fit preview and iteration table update live during optimization.', 'run_controls': 'Run controls', 'optimization_tip': 'Recommended: start with recommended_adaptive_bounds. Global methods can be slow; the GUI keeps live plots updated while running.', 'method_label': 'Method', 'max_evaluations_label': 'Max evaluations', 'regularization_label': 'Regularization', 'reg_type_label': 'Reg. type', 'validation_split_label': 'Validation split', 'workers_label': 'Workers', 'near_bound_penalty_label': 'Near-bound penalty', 'pause': 'Pause', 'stop': 'Stop', 'eval_label': 'Eval', 'objective_label': 'Objective', 'best_objective_label': 'Best objective', 'parameters_label': 'Parameters',
    'report_subtitle': 'PDF report, FEA export bundle, Excel calculator and run-folder management.', 'open_last_run_folder': 'Open last run folder', 'generate_fea_bundle': 'Generate / refresh FEA export bundle', 'generate_pdf_report': 'Generate PDF report', 'generate_excel_calculator': 'Generate Excel calculator', 'parameter_metric': 'Parameter / Metric', 'value_label': 'Value', 'report_note': 'After a completed run, HyperFitPro writes plots, logs, reports, exports, FEA target curves and plugin tools under the run folder. Use Plugin Workbench for additional report assets and audit outputs.',
    'plugin_subtitle': '50 embedded plugins are grouped by category. Run them on the current workspace or on imported .hyp2fit/.hfp projects.', 'target_project': 'Target project', 'reload_plugins': 'Reload plugins', 'run_selected': 'Run selected', 'run_category': 'Run compatible in category', 'plugin_categories': 'Plugin categories / tools', 'plugin_detail': 'Plugin detail', 'requires': 'Requires', 'outputs': 'Outputs', 'flat_plugin_list': 'Flat plugin list', 'plugin_results_subtitle': 'View plugin output files here. Results are stored in tools folders.', 'time_label': 'Time', 'target': 'Target', 'plugin': 'Plugin', 'message': 'Message', 'files': 'Files',
    'project_subtitle': 'Saved .hyp2fit or legacy .hfp projects can be imported; plugins can also run on those projects.', 'import_hyp2fit_project': 'Import .hyp2fit / .hfp project', 'load_selected_workspace': 'Load selected into workspace', 'save_current_hyp2fit': 'Save current as .hyp2fit', 'remove_selected_library': 'Remove selected from library', 'project': 'Project', 'datasets': 'Datasets', 'last_run': 'Last run', 'modified': 'Modified', 'notes': 'Notes',
    'diagnostics_subtitle': 'Run all validation checks here before GitHub release or user delivery.', 'run_selected_checks': 'Run selected checks', 'run_all_checks': 'Run all checks', 'clear_log': 'Clear log', 'available_checks': 'Available diagnostic checks', 'diagnostic_note': 'This center keeps verification checks inside the GUI. The repository root stays clean with only the main launcher.', 'diagnostic_output': 'Diagnostic output',
    'help_page_title': 'Help / User Guide', 'help_page_subtitle': 'Offline help center: 5 worked examples, annotated screens, PDF/HTML manual and troubleshooting.', 'open_pdf_manual': 'Open PDF manual', 'open_html_guide': 'Open HTML guide', 'open_help_folder': 'Open help folder', 'capture_screenshot': 'Capture current screenshot', 'help_topics': 'Help topics / annotated screens', 'help_note': 'This offline help system ships with the program. It includes five worked examples, multilingual guidance and highlighted screens.', 'select_topic': 'Select a help topic',
    'language_changed': 'Interface language changed: {language}', 'no_model_data_run': 'No model/data/run yet.', 'about_title': 'About HyperFitPro Studio', 'about_text': 'HyperFitPro Studio 1.0 is an engineering workbench for hyperelastic material calibration, reporting, plugin analysis and FEA export.',
}}

# Compact but complete UI dictionaries for German, French and Spanish. Technical terms are intentionally kept recognizable.
for code, repl in {
    'de': {'language':'Sprache','navigation':'Navigation','hide':'Ausblenden','menu':'Menü','workflow':'Arbeitsablauf','plugins':'Plugins','projects':'Projekte','tools':'Werkzeuge','dashboard':'Dashboard','model':'Modell','data_import':'Datenimport','optimization':'Optimierung','report_export':'Bericht / Export','project_library':'Projektbibliothek','diagnostics':'Verifikationszentrum','help':'Hilfe / Benutzerhandbuch','ready':'Bereit. Beginnen Sie mit Arbeitsordner, Modell und Testdaten.','select':'Auswählen','open':'Öffnen','working_directory':'Arbeitsordner','quick_actions':'Schnellaktionen','current_workspace':'Aktiver Arbeitsbereich','recommended_workflow':'Empfohlener Ablauf','session_log':'Sitzungslog','search':'Suche','category':'Kategorie','run_optimization':'Optimierung starten','pause':'Pause','stop':'Stop','import_project':'Projekt importieren','copy_model_details':'Modelldetails kopieren','help_page_title':'Hilfe / Benutzerhandbuch','language_changed':'Oberflächensprache geändert: {language}'},
    'fr': {'language':'Langue','navigation':'Navigation','hide':'Masquer','menu':'Menu','workflow':'Flux de travail','plugins':'Plugins','projects':'Projets','tools':'Outils','dashboard':'Tableau de bord','model':'Modèle','data_import':'Import des données','optimization':'Optimisation','report_export':'Rapport / Export','project_library':'Bibliothèque de projets','diagnostics':'Centre de vérification','help':'Aide / Guide utilisateur','ready':'Prêt. Commencez par le dossier de travail, le modèle et les données.','select':'Sélectionner','open':'Ouvrir','working_directory':'Dossier de travail','quick_actions':'Actions rapides','current_workspace':'Espace de travail actuel','recommended_workflow':'Flux recommandé','session_log':'Journal de session','search':'Rechercher','category':'Catégorie','run_optimization':'Lancer optimisation','pause':'Pause','stop':'Arrêter','import_project':'Importer projet','copy_model_details':'Copier détails modèle','help_page_title':'Aide / Guide utilisateur','language_changed':'Langue de l’interface modifiée : {language}'},
    'es': {'language':'Idioma','navigation':'Navegación','hide':'Ocultar','menu':'Menú','workflow':'Flujo de trabajo','plugins':'Plugins','projects':'Proyectos','tools':'Herramientas','dashboard':'Panel','model':'Modelo','data_import':'Importar datos','optimization':'Optimización','report_export':'Informe / Exportar','project_library':'Biblioteca de proyectos','diagnostics':'Centro de verificación','help':'Ayuda / Guía de usuario','ready':'Listo. Empiece con directorio, modelo y datos de ensayo.','select':'Seleccionar','open':'Abrir','working_directory':'Directorio de trabajo','quick_actions':'Acciones rápidas','current_workspace':'Espacio de trabajo actual','recommended_workflow':'Flujo recomendado','session_log':'Registro de sesión','search':'Buscar','category':'Categoría','run_optimization':'Ejecutar optimización','pause':'Pausa','stop':'Detener','import_project':'Importar proyecto','copy_model_details':'Copiar detalles del modelo','help_page_title':'Ayuda / Guía de usuario','language_changed':'Idioma de interfaz cambiado: {language}'},
}.items():
    TRANSLATIONS[code] = {**TRANSLATIONS['en'], **repl}

def tr(lang: str, key: str, **kwargs) -> str:
    lang = lang if lang in TRANSLATIONS else 'tr'
    text = TRANSLATIONS.get(lang, TRANSLATIONS['tr']).get(key, TRANSLATIONS['en'].get(key, TRANSLATIONS['tr'].get(key, key)))
    return text.format(**kwargs) if kwargs else text
